# Generated by Django 3.2.23 on 2023-12-15 21:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_media_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='release_year',
            field=models.IntegerField(validators=[blog.models.validate_year]),
        ),
    ]
