# Generated by Django 3.2.23 on 2024-01-14 19:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_post_comment_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='blogpost_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
